import { Platform, StyleSheet } from "react-native";
import type { NativeThemeColors } from "./types";

export function createDashboardStyles(colors: NativeThemeColors) {
  const lowElevation = {
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  } as const;
  const mediumElevation = {
    shadowColor: "#000",
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 8,
  } as const;
  const accentGlow = {
    shadowColor: colors.success,
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  } as const;

  return StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background, overflow: "hidden" },
  contentShell: { flex: 1, minWidth: 0, minHeight: 0, backgroundColor: colors.background },
  header: {
    paddingHorizontal: 24,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceElevated,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    ...mediumElevation,
    zIndex: 3,
  },
  title: { color: colors.midground, fontSize: 24, fontWeight: "800" },
  subtitle: { color: colors.midgroundFaint, marginTop: 4 },
  menuButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceElevated,
    alignItems: "center",
    justifyContent: "center",
    ...lowElevation,
  },
  mainMenu: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    zIndex: 20,
    width: 304,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 24,
    shadowOffset: { width: 8, height: 0 },
    elevation: 12,
  },
  connectionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceElevated,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...lowElevation,
  },
  secondaryText: { color: colors.highlight, fontWeight: "800" },
  connect: { backgroundColor: colors.success },
  disconnect: { backgroundColor: colors.destructiveSurface, borderWidth: 1, borderColor: colors.destructiveBorder },
  connectionText: { color: colors.background, fontWeight: "800" },
  disconnectText: { color: colors.destructiveText },
  paneChrome: {
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...lowElevation,
    zIndex: 2,
  },
  paneChromeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  paneChromeText: { flex: 1, minWidth: 0 },
  paneTitle: { color: colors.midground, fontSize: 20, fontWeight: "900" },
  paneSubtitle: { color: colors.midgroundFaint, marginTop: 3 },
  headerLeft: { flexDirection: "row", alignItems: "center", gap: 12, minWidth: 0, flex: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  saildashThemeToggle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceElevated,
    borderRadius: 999,
    padding: 3,
  },
  saildashThemeOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  saildashThemeOptionActive: {
    backgroundColor: colors.success,
  },
  saildashThemeOptionText: {
    color: colors.midgroundMuted,
    fontSize: 12,
    fontWeight: "900",
  },
  saildashThemeOptionTextActive: {
    color: colors.onBackground,
  },
  helpCategoryTitle: { color: colors.success, fontSize: 13, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.8 },
  helpRow: { flexDirection: "row", gap: 8, alignItems: "flex-start" },
  helpCommand: { color: colors.highlight, fontFamily: Platform.select({ web: "Menlo, monospace", default: undefined }), fontSize: 12, lineHeight: 18 },
  helpDescription: { flex: 1, color: colors.midgroundFaint, fontSize: 12, lineHeight: 18 },
  helpCategory: { gap: 4, marginTop: 12 },
  chatPane: { flex: 1, minHeight: 0, flexDirection: "row" },
  chatMain: { flex: 1, minWidth: 0, minHeight: 0, flexDirection: "column" },
  activitySidebar: {
    width: 320,
    minHeight: 0,
    alignSelf: "stretch",
    flexDirection: "column",
    borderLeftWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    ...lowElevation,
  },
  activitySidebarScroll: { flex: 1 },
  activityFeedFull: { gap: 14 },
  activityFeedCompact: { gap: 10, padding: 14, paddingBottom: 24 },
  transcript: { flex: 1 },
  transcriptContent: { padding: 24, gap: 14 },
  bubble: { maxWidth: 900, alignSelf: "flex-start", backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 16, ...lowElevation },
  userBubble: { alignSelf: "flex-end", backgroundColor: colors.accentStrong, borderColor: colors.borderStrong, ...accentGlow },
  systemBubble: { backgroundColor: colors.systemSurface, borderColor: colors.systemBorder },
  role: { color: colors.success, fontSize: 12, fontWeight: "800", textTransform: "uppercase", marginBottom: 8 },
  userRole: { color: colors.midground },
  systemRole: { color: colors.systemText },
  messageText: { color: colors.midground, fontSize: 15, lineHeight: 22, userSelect: "text" as any },
  userText: { color: colors.midground },
  systemText: { color: colors.systemText },
  emptyState: { marginTop: 24, maxWidth: 720, alignSelf: "center", gap: 14, padding: 24, borderWidth: 1, borderColor: colors.border, borderRadius: 20, backgroundColor: colors.surfaceElevated, ...mediumElevation },
  compactEmptyState: { marginTop: 12, gap: 8, padding: 14, borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surfaceElevated, ...lowElevation },
  emptyTitle: { color: colors.midground, fontSize: 24, fontWeight: "800" },
  compactEmptyTitle: { color: colors.midground, fontSize: 15, fontWeight: "800" },
  emptyText: { color: colors.midgroundFaint, fontSize: 16, lineHeight: 24 },
  compactEmptyText: { color: colors.midgroundFaint, fontSize: 12, lineHeight: 18 },
  emptyCode: { color: colors.success, fontFamily: Platform.select({ web: "Menlo, monospace", default: undefined }), backgroundColor: colors.background, padding: 12, borderRadius: 10 },
  composerShell: { padding: 16, gap: 10, borderTopWidth: 1, borderColor: colors.borderStrong, backgroundColor: colors.surfaceElevated, ...mediumElevation },
  composer: { flexDirection: "row", alignItems: "flex-end", gap: 12 },
  attachmentTray: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  attachmentChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    maxWidth: 320,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 999,
    backgroundColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  attachmentTextBlock: { minWidth: 0, flexShrink: 1 },
  attachmentName: { color: colors.highlight, fontSize: 12, fontWeight: "900" },
  attachmentMeta: { color: colors.midgroundFaint, fontSize: 11, marginTop: 2 },
  attachmentMessage: { color: colors.midgroundFaint, fontSize: 12, lineHeight: 17, flexShrink: 1 },
  slashPalette: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surfaceElevated,
    overflow: "hidden",
    ...mediumElevation,
  },
  slashPaletteHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  slashPaletteTitle: { color: colors.midground, fontWeight: "900", fontSize: 12 },
  slashPaletteHint: { color: colors.midgroundMuted, fontSize: 11 },
  slashCompletionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  slashCompletionText: {
    minWidth: 110,
    color: colors.success,
    fontFamily: Platform.select({ web: "Menlo, monospace", default: undefined }),
    fontWeight: "900",
    fontSize: 12,
  },
  slashCompletionMeta: { color: colors.midgroundFaint, fontSize: 12, flex: 1 },
  slashMessage: { color: colors.systemText, fontSize: 12, lineHeight: 17 },
  chatModeWrap: { gap: 6 },
  chatModeToggle: {
    flexDirection: "row",
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: colors.surfaceElevated,
    padding: 3,
    gap: 2,
  },
  chatModeButton: {
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chatModeButtonActive: {
    backgroundColor: colors.success,
  },
  chatModeButtonText: {
    color: colors.midgroundFaint,
    fontSize: 12,
    fontWeight: "800",
  },
  chatModeButtonTextActive: {
    color: colors.background,
  },
  chatModeDescription: {
    color: colors.midgroundMuted,
    fontSize: 11,
    lineHeight: 16,
  },
  clearAttachmentButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: colors.destructiveBorder,
    borderRadius: 999,
    backgroundColor: colors.destructiveSurface,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  clearAttachmentText: { color: colors.destructiveText, fontSize: 12, fontWeight: "900" },
  input: { flex: 1, minHeight: 48, maxHeight: 160, color: colors.midground, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, ...lowElevation },
  sendButton: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: colors.success, paddingHorizontal: 16, paddingVertical: 14, borderRadius: 14, ...accentGlow },
  stopOnlyButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.destructiveSurface,
    borderWidth: 1,
    borderColor: colors.destructiveBorder,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 14,
  },
  stopButton: { backgroundColor: colors.destructiveSurface, borderWidth: 1, borderColor: colors.destructiveBorder },
  sendDisabled: { opacity: 0.45 },
  sendText: { color: colors.background, fontWeight: "900" },
  stopText: { color: colors.destructiveText },
  fullPane: { flex: 1 },
  fullPaneContent: {
    width: "100%",
    maxWidth: 1280,
    alignSelf: "center",
    paddingHorizontal: 32,
    paddingVertical: 28,
    gap: 18,
  },
  panelHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14, marginBottom: 4 },
  sectionTitle: { color: colors.midground, fontSize: 18, fontWeight: "900" },
  sectionSubtitle: { color: colors.midgroundFaint, marginTop: 4 },
  sessionCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, backgroundColor: colors.surfaceElevated , ...mediumElevation },
  sessionTitle: { color: colors.midground, fontWeight: "800", fontSize: 15 },
  sessionMeta: { color: colors.midgroundMuted, marginTop: 4, fontSize: 12 },
  sessionPreview: { color: colors.midgroundFaint, marginTop: 9, fontSize: 13, lineHeight: 18 },
  toolCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, backgroundColor: colors.surfaceElevated , ...mediumElevation },
  toolName: { color: colors.success, fontWeight: "800" },
  toolStatus: { color: colors.midgroundFaint, marginTop: 2 },
  toolPreview: { color: colors.midgroundFaint, marginTop: 8, fontSize: 12, lineHeight: 18 },
  settingsToolbar: { width: "100%", maxWidth: 1180, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 14 },
  settingsHeaderCard: { width: "100%", maxWidth: 1180, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 18, backgroundColor: colors.surfaceElevated, gap: 12 , ...mediumElevation },
  inlineIconText: { flexDirection: "row", alignItems: "center", gap: 8 },
  providerBlock: { flexGrow: 1, flexBasis: 340, minWidth: 280, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, backgroundColor: colors.surface, gap: 10 },
  settingBlock: { gap: 8, paddingTop: 4 },
  choiceChip: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", alignItems: "center", gap: 6, maxWidth: "100%" },
  choiceChipActive: { backgroundColor: colors.success, borderColor: colors.borderStrong, ...accentGlow },
  choiceChipDisabled: { opacity: 0.45 },
  choiceChipText: { color: colors.midgroundFaint, fontWeight: "800", fontSize: 12 },
  choiceChipTextActive: { color: colors.background },
  miniBadge: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3, backgroundColor: colors.background },
  miniBadgeOn: { borderColor: colors.success, backgroundColor: colors.accentStrong },
  miniBadgeText: { color: colors.midgroundFaint, fontSize: 11, fontWeight: "900" },
  miniBadgeTextOn: { color: colors.highlight },
  settingsMessage: { width: "100%", maxWidth: 1180, color: colors.midground, backgroundColor: colors.surfaceElevated, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12 },
  settingsGrid: { width: "100%", maxWidth: 1180, flexDirection: "row", flexWrap: "wrap", gap: 16, alignItems: "stretch" },
  settingsCard: { width: "100%", maxWidth: 1180, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 20, backgroundColor: colors.surfaceElevated, gap: 14 , ...mediumElevation },
  settingsCardWide: { width: "100%", maxWidth: 1180, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 20, backgroundColor: colors.surfaceElevated, gap: 14 , ...mediumElevation },
  optionGroup: { gap: 8 },
  chipWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, alignItems: "center" },
  optionButton: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, borderRadius: 999, paddingHorizontal: 12, paddingVertical: 8 },
  optionButtonActive: { backgroundColor: colors.accentStrong, borderColor: colors.borderStrong, ...accentGlow },
  optionButtonText: { color: colors.midgroundFaint, fontWeight: "800", fontSize: 12 },
  optionButtonTextActive: { color: colors.highlight },
  statusPill: { color: colors.midgroundFaint, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, overflow: "hidden" },
  statusPillActive: { color: colors.highlight, borderColor: colors.borderStrong, backgroundColor: colors.accentStrong },
  inlineInputs: { flexDirection: "row", gap: 8, alignItems: "center" },
  inlineInput: { flex: 1, minWidth: 0 },
  toolsetGrid: { width: "100%", flexDirection: "row", flexWrap: "wrap", gap: 12, alignItems: "stretch" },
  toolsetCard: { flexGrow: 1, flexBasis: 240, minWidth: 220, maxWidth: 360, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, backgroundColor: colors.surface, gap: 8 },
  toolsetCardEnabled: { borderColor: colors.borderStrong, backgroundColor: colors.accent },
  toolsetCardOn: { borderColor: colors.borderStrong, backgroundColor: colors.accent },
  toolsetTitle: { color: colors.midground, fontWeight: "900" },
  toolsetMeta: { color: colors.success, fontSize: 12 },
  toolsetDescription: { color: colors.midgroundFaint, fontSize: 12, lineHeight: 17 },
  urlInput: { color: colors.midground, backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 12 },
  infoRow: { borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, gap: 4 },
  infoLabel: { color: colors.midgroundMuted, fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.9 },
  infoValue: { color: colors.midground, fontSize: 13, lineHeight: 19 },
  listRow: { borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 12, backgroundColor: colors.surface, gap: 6 },
  settingHelp: { color: colors.midgroundFaint, lineHeight: 20 },
  settingRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingVertical: 4 },
  settingRowText: { flex: 1, minWidth: 0, gap: 6 },
  settingRowTitle: { color: colors.midground, fontWeight: "800", fontSize: 15 },
  toggle: { width: 46, height: 28, borderRadius: 999, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, padding: 3, justifyContent: "center" },
  toggleOn: { backgroundColor: colors.accentStrong, borderColor: colors.borderStrong, ...accentGlow },
  toggleKnob: { width: 20, height: 20, borderRadius: 999, backgroundColor: colors.midgroundMuted },
  toggleKnobOn: { alignSelf: "flex-end", backgroundColor: colors.midground },
  missionControlBanner: {
    marginHorizontal: 24,
    marginTop: 12,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    backgroundColor: colors.accent,
    borderRadius: 16,
    padding: 14,
  },
  missionControlBannerText: { color: colors.highlight, fontWeight: "800", textAlign: "center" },
  card: { width: "100%", maxWidth: 1180, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 20, backgroundColor: colors.surfaceElevated, gap: 14 , ...mediumElevation },
  cardWide: { maxWidth: 1280 },
  sectionHeader: { gap: 4 },
  disabled: { opacity: 0.45 },
  });
}

export type DashboardStyles = ReturnType<typeof createDashboardStyles>;
